// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: auth.proto

package cloudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorCode int32

const (
	AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED        AuthErrorCode = 0
	AuthErrorCode_AUTH_ERROR_CODE_INVALID_CREDENTIAL AuthErrorCode = 1
	AuthErrorCode_AUTH_ERROR_CODE_KEY_DISABLED       AuthErrorCode = 2
	AuthErrorCode_AUTH_ERROR_CODE_KEY_EXPIRED        AuthErrorCode = 3
	AuthErrorCode_AUTH_ERROR_CODE_SITE_DISABLED      AuthErrorCode = 4
	AuthErrorCode_AUTH_ERROR_CODE_INTERNAL_ERROR     AuthErrorCode = 5
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0: "AUTH_ERROR_CODE_UNSPECIFIED",
		1: "AUTH_ERROR_CODE_INVALID_CREDENTIAL",
		2: "AUTH_ERROR_CODE_KEY_DISABLED",
		3: "AUTH_ERROR_CODE_KEY_EXPIRED",
		4: "AUTH_ERROR_CODE_SITE_DISABLED",
		5: "AUTH_ERROR_CODE_INTERNAL_ERROR",
	}
	AuthErrorCode_value = map[string]int32{
		"AUTH_ERROR_CODE_UNSPECIFIED":        0,
		"AUTH_ERROR_CODE_INVALID_CREDENTIAL": 1,
		"AUTH_ERROR_CODE_KEY_DISABLED":       2,
		"AUTH_ERROR_CODE_KEY_EXPIRED":        3,
		"AUTH_ERROR_CODE_SITE_DISABLED":      4,
		"AUTH_ERROR_CODE_INTERNAL_ERROR":     5,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type ExchangeCredentialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CredentialBase64 string                 `protobuf:"bytes,1,opt,name=credential_base64,json=credentialBase64,proto3" json:"credential_base64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExchangeCredentialRequest) Reset() {
	*x = ExchangeCredentialRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCredentialRequest) ProtoMessage() {}

func (x *ExchangeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCredentialRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeCredentialRequest) GetCredentialBase64() string {
	if x != nil {
		return x.CredentialBase64
	}
	return ""
}

type ExchangeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	KeyId         string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,5,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCredentialResponse) Reset() {
	*x = ExchangeCredentialResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCredentialResponse) ProtoMessage() {}

func (x *ExchangeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCredentialResponse.ProtoReflect.Descriptor instead.
func (*ExchangeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeCredentialResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeCredentialResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ExchangeCredentialResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeCredentialResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ExchangeCredentialResponse) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x11archebase.auth.v1\x1a\fcommon.proto\"H\n" +
	"\x19ExchangeCredentialRequest\x12+\n" +
	"\x11credential_base64\x18\x01 \x01(\tR\x10credentialBase64\"\xbc\x01\n" +
	"\x1aExchangeCredentialResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x05 \x01(\tR\tkeyPrefix*\xe2\x01\n" +
	"\rAuthErrorCode\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"AUTH_ERROR_CODE_INVALID_CREDENTIAL\x10\x01\x12 \n" +
	"\x1cAUTH_ERROR_CODE_KEY_DISABLED\x10\x02\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_KEY_EXPIRED\x10\x03\x12!\n" +
	"\x1dAUTH_ERROR_CODE_SITE_DISABLED\x10\x04\x12\"\n" +
	"\x1eAUTH_ERROR_CODE_INTERNAL_ERROR\x10\x052\x80\x01\n" +
	"\vAuthService\x12q\n" +
	"\x12ExchangeCredential\x12,.archebase.auth.v1.ExchangeCredentialRequest\x1a-.archebase.auth.v1.ExchangeCredentialResponseb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_proto_goTypes = []any{
	(AuthErrorCode)(0),                 // 0: archebase.auth.v1.AuthErrorCode
	(*ExchangeCredentialRequest)(nil),  // 1: archebase.auth.v1.ExchangeCredentialRequest
	(*ExchangeCredentialResponse)(nil), // 2: archebase.auth.v1.ExchangeCredentialResponse
}
var file_auth_proto_depIdxs = []int32{
	1, // 0: archebase.auth.v1.AuthService.ExchangeCredential:input_type -> archebase.auth.v1.ExchangeCredentialRequest
	2, // 1: archebase.auth.v1.AuthService.ExchangeCredential:output_type -> archebase.auth.v1.ExchangeCredentialResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
