// SPDX-FileCopyrightText: 2026 ArcheBase
// SPDX-License-Identifier: MulanPSL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: data_gateway.proto

package cloudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataGatewayService_CreateLogicalUpload_FullMethodName      = "/archebase.data_gateway.v1.DataGatewayService/CreateLogicalUpload"
	DataGatewayService_GetUploadRecovery_FullMethodName        = "/archebase.data_gateway.v1.DataGatewayService/GetUploadRecovery"
	DataGatewayService_ReissueUploadCredentials_FullMethodName = "/archebase.data_gateway.v1.DataGatewayService/ReissueUploadCredentials"
	DataGatewayService_AbortUpload_FullMethodName              = "/archebase.data_gateway.v1.DataGatewayService/AbortUpload"
	DataGatewayService_CompleteUpload_FullMethodName           = "/archebase.data_gateway.v1.DataGatewayService/CompleteUpload"
)

// DataGatewayServiceClient is the client API for DataGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGatewayServiceClient interface {
	// Upload RPCs are scoped exclusively by the bearer API-key principal
	// stamped by the public interceptor. Clients never send site_id or any
	// other owner identifier on this surface.
	CreateLogicalUpload(ctx context.Context, in *CreateLogicalUploadRequest, opts ...grpc.CallOption) (*CreateLogicalUploadResponse, error)
	GetUploadRecovery(ctx context.Context, in *GetUploadRecoveryRequest, opts ...grpc.CallOption) (*GetUploadRecoveryResponse, error)
	ReissueUploadCredentials(ctx context.Context, in *ReissueUploadCredentialsRequest, opts ...grpc.CallOption) (*ReissueUploadCredentialsResponse, error)
	AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*AbortUploadResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
}

type dataGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayServiceClient(cc grpc.ClientConnInterface) DataGatewayServiceClient {
	return &dataGatewayServiceClient{cc}
}

func (c *dataGatewayServiceClient) CreateLogicalUpload(ctx context.Context, in *CreateLogicalUploadRequest, opts ...grpc.CallOption) (*CreateLogicalUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogicalUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CreateLogicalUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) GetUploadRecovery(ctx context.Context, in *GetUploadRecoveryRequest, opts ...grpc.CallOption) (*GetUploadRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadRecoveryResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_GetUploadRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) ReissueUploadCredentials(ctx context.Context, in *ReissueUploadCredentialsRequest, opts ...grpc.CallOption) (*ReissueUploadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReissueUploadCredentialsResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_ReissueUploadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*AbortUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_AbortUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayServiceServer is the server API for DataGatewayService service.
// All implementations must embed UnimplementedDataGatewayServiceServer
// for forward compatibility.
type DataGatewayServiceServer interface {
	// Upload RPCs are scoped exclusively by the bearer API-key principal
	// stamped by the public interceptor. Clients never send site_id or any
	// other owner identifier on this surface.
	CreateLogicalUpload(context.Context, *CreateLogicalUploadRequest) (*CreateLogicalUploadResponse, error)
	GetUploadRecovery(context.Context, *GetUploadRecoveryRequest) (*GetUploadRecoveryResponse, error)
	ReissueUploadCredentials(context.Context, *ReissueUploadCredentialsRequest) (*ReissueUploadCredentialsResponse, error)
	AbortUpload(context.Context, *AbortUploadRequest) (*AbortUploadResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	mustEmbedUnimplementedDataGatewayServiceServer()
}

// UnimplementedDataGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayServiceServer struct{}

func (UnimplementedDataGatewayServiceServer) CreateLogicalUpload(context.Context, *CreateLogicalUploadRequest) (*CreateLogicalUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLogicalUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) GetUploadRecovery(context.Context, *GetUploadRecoveryRequest) (*GetUploadRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadRecovery not implemented")
}
func (UnimplementedDataGatewayServiceServer) ReissueUploadCredentials(context.Context, *ReissueUploadCredentialsRequest) (*ReissueUploadCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReissueUploadCredentials not implemented")
}
func (UnimplementedDataGatewayServiceServer) AbortUpload(context.Context, *AbortUploadRequest) (*AbortUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) mustEmbedUnimplementedDataGatewayServiceServer() {}
func (UnimplementedDataGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeDataGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayServiceServer will
// result in compilation errors.
type UnsafeDataGatewayServiceServer interface {
	mustEmbedUnimplementedDataGatewayServiceServer()
}

func RegisterDataGatewayServiceServer(s grpc.ServiceRegistrar, srv DataGatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGatewayService_ServiceDesc, srv)
}

func _DataGatewayService_CreateLogicalUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogicalUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CreateLogicalUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CreateLogicalUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CreateLogicalUpload(ctx, req.(*CreateLogicalUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_GetUploadRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).GetUploadRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_GetUploadRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).GetUploadRecovery(ctx, req.(*GetUploadRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_ReissueUploadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReissueUploadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).ReissueUploadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_ReissueUploadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).ReissueUploadCredentials(ctx, req.(*ReissueUploadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_AbortUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).AbortUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_AbortUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).AbortUpload(ctx, req.(*AbortUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGatewayService_ServiceDesc is the grpc.ServiceDesc for DataGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DataGatewayService",
	HandlerType: (*DataGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLogicalUpload",
			Handler:    _DataGatewayService_CreateLogicalUpload_Handler,
		},
		{
			MethodName: "GetUploadRecovery",
			Handler:    _DataGatewayService_GetUploadRecovery_Handler,
		},
		{
			MethodName: "ReissueUploadCredentials",
			Handler:    _DataGatewayService_ReissueUploadCredentials_Handler,
		},
		{
			MethodName: "AbortUpload",
			Handler:    _DataGatewayService_AbortUpload_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _DataGatewayService_CompleteUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}

const (
	DataGatewayObjectService_ListObjects_FullMethodName     = "/archebase.data_gateway.v1.DataGatewayObjectService/ListObjects"
	DataGatewayObjectService_RequestDownload_FullMethodName = "/archebase.data_gateway.v1.DataGatewayObjectService/RequestDownload"
)

// DataGatewayObjectServiceClient is the client API for DataGatewayObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SDK-facing object discovery and download authorization service exposed on
// the public gRPC port.
//
// This service uses user access JWT authentication. Object listing returns
// logical object IDs visible to the caller; download returns short-lived
// presigned read operations rather than cloud credentials.
type DataGatewayObjectServiceClient interface {
	// Lists verified logical objects visible to the authenticated user.
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	// Authorizes direct object downloads for the requested file IDs.
	RequestDownload(ctx context.Context, in *RequestDownloadRequest, opts ...grpc.CallOption) (*RequestDownloadResponse, error)
}

type dataGatewayObjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayObjectServiceClient(cc grpc.ClientConnInterface) DataGatewayObjectServiceClient {
	return &dataGatewayObjectServiceClient{cc}
}

func (c *dataGatewayObjectServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, DataGatewayObjectService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayObjectServiceClient) RequestDownload(ctx context.Context, in *RequestDownloadRequest, opts ...grpc.CallOption) (*RequestDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestDownloadResponse)
	err := c.cc.Invoke(ctx, DataGatewayObjectService_RequestDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayObjectServiceServer is the server API for DataGatewayObjectService service.
// All implementations must embed UnimplementedDataGatewayObjectServiceServer
// for forward compatibility.
//
// SDK-facing object discovery and download authorization service exposed on
// the public gRPC port.
//
// This service uses user access JWT authentication. Object listing returns
// logical object IDs visible to the caller; download returns short-lived
// presigned read operations rather than cloud credentials.
type DataGatewayObjectServiceServer interface {
	// Lists verified logical objects visible to the authenticated user.
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	// Authorizes direct object downloads for the requested file IDs.
	RequestDownload(context.Context, *RequestDownloadRequest) (*RequestDownloadResponse, error)
	mustEmbedUnimplementedDataGatewayObjectServiceServer()
}

// UnimplementedDataGatewayObjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayObjectServiceServer struct{}

func (UnimplementedDataGatewayObjectServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedDataGatewayObjectServiceServer) RequestDownload(context.Context, *RequestDownloadRequest) (*RequestDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDownload not implemented")
}
func (UnimplementedDataGatewayObjectServiceServer) mustEmbedUnimplementedDataGatewayObjectServiceServer() {
}
func (UnimplementedDataGatewayObjectServiceServer) testEmbeddedByValue() {}

// UnsafeDataGatewayObjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayObjectServiceServer will
// result in compilation errors.
type UnsafeDataGatewayObjectServiceServer interface {
	mustEmbedUnimplementedDataGatewayObjectServiceServer()
}

func RegisterDataGatewayObjectServiceServer(s grpc.ServiceRegistrar, srv DataGatewayObjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataGatewayObjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGatewayObjectService_ServiceDesc, srv)
}

func _DataGatewayObjectService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayObjectServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayObjectService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayObjectServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayObjectService_RequestDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayObjectServiceServer).RequestDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayObjectService_RequestDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayObjectServiceServer).RequestDownload(ctx, req.(*RequestDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGatewayObjectService_ServiceDesc is the grpc.ServiceDesc for DataGatewayObjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGatewayObjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DataGatewayObjectService",
	HandlerType: (*DataGatewayObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListObjects",
			Handler:    _DataGatewayObjectService_ListObjects_Handler,
		},
		{
			MethodName: "RequestDownload",
			Handler:    _DataGatewayObjectService_RequestDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}

const (
	DataGatewayCopyService_CreateCopyJob_FullMethodName    = "/archebase.data_gateway.v1.DataGatewayCopyService/CreateCopyJob"
	DataGatewayCopyService_GetCopyJob_FullMethodName       = "/archebase.data_gateway.v1.DataGatewayCopyService/GetCopyJob"
	DataGatewayCopyService_ListCopyJobItems_FullMethodName = "/archebase.data_gateway.v1.DataGatewayCopyService/ListCopyJobItems"
	DataGatewayCopyService_CancelCopyJob_FullMethodName    = "/archebase.data_gateway.v1.DataGatewayCopyService/CancelCopyJob"
)

// DataGatewayCopyServiceClient is the client API for DataGatewayCopyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SDK-facing asynchronous object copy service exposed on the public gRPC port.
//
// This service accepts logical file IDs and persists copy jobs for background
// workers. It never exposes source OSS bucket, object key, or source-side
// credentials to the caller.
type DataGatewayCopyServiceClient interface {
	// Creates an asynchronous copy job for the requested file IDs.
	CreateCopyJob(ctx context.Context, in *CreateCopyJobRequest, opts ...grpc.CallOption) (*CreateCopyJobResponse, error)
	// Returns the aggregate state of one copy job.
	GetCopyJob(ctx context.Context, in *GetCopyJobRequest, opts ...grpc.CallOption) (*GetCopyJobResponse, error)
	// Lists item-level copy outcomes for one copy job.
	ListCopyJobItems(ctx context.Context, in *ListCopyJobItemsRequest, opts ...grpc.CallOption) (*ListCopyJobItemsResponse, error)
	// Requests cancellation of one copy job.
	CancelCopyJob(ctx context.Context, in *CancelCopyJobRequest, opts ...grpc.CallOption) (*CancelCopyJobResponse, error)
}

type dataGatewayCopyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayCopyServiceClient(cc grpc.ClientConnInterface) DataGatewayCopyServiceClient {
	return &dataGatewayCopyServiceClient{cc}
}

func (c *dataGatewayCopyServiceClient) CreateCopyJob(ctx context.Context, in *CreateCopyJobRequest, opts ...grpc.CallOption) (*CreateCopyJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCopyJobResponse)
	err := c.cc.Invoke(ctx, DataGatewayCopyService_CreateCopyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayCopyServiceClient) GetCopyJob(ctx context.Context, in *GetCopyJobRequest, opts ...grpc.CallOption) (*GetCopyJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCopyJobResponse)
	err := c.cc.Invoke(ctx, DataGatewayCopyService_GetCopyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayCopyServiceClient) ListCopyJobItems(ctx context.Context, in *ListCopyJobItemsRequest, opts ...grpc.CallOption) (*ListCopyJobItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCopyJobItemsResponse)
	err := c.cc.Invoke(ctx, DataGatewayCopyService_ListCopyJobItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayCopyServiceClient) CancelCopyJob(ctx context.Context, in *CancelCopyJobRequest, opts ...grpc.CallOption) (*CancelCopyJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCopyJobResponse)
	err := c.cc.Invoke(ctx, DataGatewayCopyService_CancelCopyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayCopyServiceServer is the server API for DataGatewayCopyService service.
// All implementations must embed UnimplementedDataGatewayCopyServiceServer
// for forward compatibility.
//
// SDK-facing asynchronous object copy service exposed on the public gRPC port.
//
// This service accepts logical file IDs and persists copy jobs for background
// workers. It never exposes source OSS bucket, object key, or source-side
// credentials to the caller.
type DataGatewayCopyServiceServer interface {
	// Creates an asynchronous copy job for the requested file IDs.
	CreateCopyJob(context.Context, *CreateCopyJobRequest) (*CreateCopyJobResponse, error)
	// Returns the aggregate state of one copy job.
	GetCopyJob(context.Context, *GetCopyJobRequest) (*GetCopyJobResponse, error)
	// Lists item-level copy outcomes for one copy job.
	ListCopyJobItems(context.Context, *ListCopyJobItemsRequest) (*ListCopyJobItemsResponse, error)
	// Requests cancellation of one copy job.
	CancelCopyJob(context.Context, *CancelCopyJobRequest) (*CancelCopyJobResponse, error)
	mustEmbedUnimplementedDataGatewayCopyServiceServer()
}

// UnimplementedDataGatewayCopyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayCopyServiceServer struct{}

func (UnimplementedDataGatewayCopyServiceServer) CreateCopyJob(context.Context, *CreateCopyJobRequest) (*CreateCopyJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCopyJob not implemented")
}
func (UnimplementedDataGatewayCopyServiceServer) GetCopyJob(context.Context, *GetCopyJobRequest) (*GetCopyJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCopyJob not implemented")
}
func (UnimplementedDataGatewayCopyServiceServer) ListCopyJobItems(context.Context, *ListCopyJobItemsRequest) (*ListCopyJobItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCopyJobItems not implemented")
}
func (UnimplementedDataGatewayCopyServiceServer) CancelCopyJob(context.Context, *CancelCopyJobRequest) (*CancelCopyJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCopyJob not implemented")
}
func (UnimplementedDataGatewayCopyServiceServer) mustEmbedUnimplementedDataGatewayCopyServiceServer() {
}
func (UnimplementedDataGatewayCopyServiceServer) testEmbeddedByValue() {}

// UnsafeDataGatewayCopyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayCopyServiceServer will
// result in compilation errors.
type UnsafeDataGatewayCopyServiceServer interface {
	mustEmbedUnimplementedDataGatewayCopyServiceServer()
}

func RegisterDataGatewayCopyServiceServer(s grpc.ServiceRegistrar, srv DataGatewayCopyServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataGatewayCopyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGatewayCopyService_ServiceDesc, srv)
}

func _DataGatewayCopyService_CreateCopyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCopyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayCopyServiceServer).CreateCopyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayCopyService_CreateCopyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayCopyServiceServer).CreateCopyJob(ctx, req.(*CreateCopyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayCopyService_GetCopyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCopyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayCopyServiceServer).GetCopyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayCopyService_GetCopyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayCopyServiceServer).GetCopyJob(ctx, req.(*GetCopyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayCopyService_ListCopyJobItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCopyJobItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayCopyServiceServer).ListCopyJobItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayCopyService_ListCopyJobItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayCopyServiceServer).ListCopyJobItems(ctx, req.(*ListCopyJobItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayCopyService_CancelCopyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCopyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayCopyServiceServer).CancelCopyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayCopyService_CancelCopyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayCopyServiceServer).CancelCopyJob(ctx, req.(*CancelCopyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGatewayCopyService_ServiceDesc is the grpc.ServiceDesc for DataGatewayCopyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGatewayCopyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DataGatewayCopyService",
	HandlerType: (*DataGatewayCopyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCopyJob",
			Handler:    _DataGatewayCopyService_CreateCopyJob_Handler,
		},
		{
			MethodName: "GetCopyJob",
			Handler:    _DataGatewayCopyService_GetCopyJob_Handler,
		},
		{
			MethodName: "ListCopyJobItems",
			Handler:    _DataGatewayCopyService_ListCopyJobItems_Handler,
		},
		{
			MethodName: "CancelCopyJob",
			Handler:    _DataGatewayCopyService_CancelCopyJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}

const (
	DeviceInitService_InitDevice_FullMethodName   = "/archebase.data_gateway.v1.DeviceInitService/InitDevice"
	DeviceInitService_ReinitDevice_FullMethodName = "/archebase.data_gateway.v1.DeviceInitService/ReinitDevice"
)

// DeviceInitServiceClient is the client API for DeviceInitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SDK-facing device initialization service exposed on the dedicated init port.
//
// This surface intentionally does not require the upload API key because it is
// used to provision that key for a registered device. Deployment-level network
// controls and rate limiting are required before exposing it outside controlled
// environments.
type DeviceInitServiceClient interface {
	// Initializes one registered device and returns the upload API key.
	InitDevice(ctx context.Context, in *InitDeviceRequest, opts ...grpc.CallOption) (*InitDeviceResponse, error)
	// Re-initializes one registered device and returns a rotated upload API key.
	ReinitDevice(ctx context.Context, in *ReinitDeviceRequest, opts ...grpc.CallOption) (*InitDeviceResponse, error)
}

type deviceInitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceInitServiceClient(cc grpc.ClientConnInterface) DeviceInitServiceClient {
	return &deviceInitServiceClient{cc}
}

func (c *deviceInitServiceClient) InitDevice(ctx context.Context, in *InitDeviceRequest, opts ...grpc.CallOption) (*InitDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceInitService_InitDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceInitServiceClient) ReinitDevice(ctx context.Context, in *ReinitDeviceRequest, opts ...grpc.CallOption) (*InitDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceInitService_ReinitDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceInitServiceServer is the server API for DeviceInitService service.
// All implementations must embed UnimplementedDeviceInitServiceServer
// for forward compatibility.
//
// SDK-facing device initialization service exposed on the dedicated init port.
//
// This surface intentionally does not require the upload API key because it is
// used to provision that key for a registered device. Deployment-level network
// controls and rate limiting are required before exposing it outside controlled
// environments.
type DeviceInitServiceServer interface {
	// Initializes one registered device and returns the upload API key.
	InitDevice(context.Context, *InitDeviceRequest) (*InitDeviceResponse, error)
	// Re-initializes one registered device and returns a rotated upload API key.
	ReinitDevice(context.Context, *ReinitDeviceRequest) (*InitDeviceResponse, error)
	mustEmbedUnimplementedDeviceInitServiceServer()
}

// UnimplementedDeviceInitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceInitServiceServer struct{}

func (UnimplementedDeviceInitServiceServer) InitDevice(context.Context, *InitDeviceRequest) (*InitDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDevice not implemented")
}
func (UnimplementedDeviceInitServiceServer) ReinitDevice(context.Context, *ReinitDeviceRequest) (*InitDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReinitDevice not implemented")
}
func (UnimplementedDeviceInitServiceServer) mustEmbedUnimplementedDeviceInitServiceServer() {}
func (UnimplementedDeviceInitServiceServer) testEmbeddedByValue()                           {}

// UnsafeDeviceInitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceInitServiceServer will
// result in compilation errors.
type UnsafeDeviceInitServiceServer interface {
	mustEmbedUnimplementedDeviceInitServiceServer()
}

func RegisterDeviceInitServiceServer(s grpc.ServiceRegistrar, srv DeviceInitServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeviceInitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceInitService_ServiceDesc, srv)
}

func _DeviceInitService_InitDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceInitServiceServer).InitDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceInitService_InitDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceInitServiceServer).InitDevice(ctx, req.(*InitDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceInitService_ReinitDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReinitDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceInitServiceServer).ReinitDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceInitService_ReinitDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceInitServiceServer).ReinitDevice(ctx, req.(*ReinitDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceInitService_ServiceDesc is the grpc.ServiceDesc for DeviceInitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceInitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DeviceInitService",
	HandlerType: (*DeviceInitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitDevice",
			Handler:    _DeviceInitService_InitDevice_Handler,
		},
		{
			MethodName: "ReinitDevice",
			Handler:    _DeviceInitService_ReinitDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}

const (
	InternalStorageService_PresignObject_FullMethodName = "/archebase.data_gateway.v1.InternalStorageService/PresignObject"
	InternalStorageService_ReadObject_FullMethodName    = "/archebase.data_gateway.v1.InternalStorageService/ReadObject"
)

// InternalStorageServiceClient is the client API for InternalStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal-only storage service exposed by data-gateway.
// This service is served on a dedicated internal gRPC port and is not
// protected by the public JWT interceptor chain.
type InternalStorageServiceClient interface {
	// Generates presigned access for a single object.
	PresignObject(ctx context.Context, in *PresignObjectRequest, opts ...grpc.CallOption) (*PresignObjectResponse, error)
	// Reads a bounded object payload for backend-only callers.
	ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (*ReadObjectResponse, error)
}

type internalStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalStorageServiceClient(cc grpc.ClientConnInterface) InternalStorageServiceClient {
	return &internalStorageServiceClient{cc}
}

func (c *internalStorageServiceClient) PresignObject(ctx context.Context, in *PresignObjectRequest, opts ...grpc.CallOption) (*PresignObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignObjectResponse)
	err := c.cc.Invoke(ctx, InternalStorageService_PresignObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalStorageServiceClient) ReadObject(ctx context.Context, in *ReadObjectRequest, opts ...grpc.CallOption) (*ReadObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadObjectResponse)
	err := c.cc.Invoke(ctx, InternalStorageService_ReadObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalStorageServiceServer is the server API for InternalStorageService service.
// All implementations must embed UnimplementedInternalStorageServiceServer
// for forward compatibility.
//
// Internal-only storage service exposed by data-gateway.
// This service is served on a dedicated internal gRPC port and is not
// protected by the public JWT interceptor chain.
type InternalStorageServiceServer interface {
	// Generates presigned access for a single object.
	PresignObject(context.Context, *PresignObjectRequest) (*PresignObjectResponse, error)
	// Reads a bounded object payload for backend-only callers.
	ReadObject(context.Context, *ReadObjectRequest) (*ReadObjectResponse, error)
	mustEmbedUnimplementedInternalStorageServiceServer()
}

// UnimplementedInternalStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalStorageServiceServer struct{}

func (UnimplementedInternalStorageServiceServer) PresignObject(context.Context, *PresignObjectRequest) (*PresignObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignObject not implemented")
}
func (UnimplementedInternalStorageServiceServer) ReadObject(context.Context, *ReadObjectRequest) (*ReadObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadObject not implemented")
}
func (UnimplementedInternalStorageServiceServer) mustEmbedUnimplementedInternalStorageServiceServer() {
}
func (UnimplementedInternalStorageServiceServer) testEmbeddedByValue() {}

// UnsafeInternalStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalStorageServiceServer will
// result in compilation errors.
type UnsafeInternalStorageServiceServer interface {
	mustEmbedUnimplementedInternalStorageServiceServer()
}

func RegisterInternalStorageServiceServer(s grpc.ServiceRegistrar, srv InternalStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalStorageService_ServiceDesc, srv)
}

func _InternalStorageService_PresignObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStorageServiceServer).PresignObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalStorageService_PresignObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStorageServiceServer).PresignObject(ctx, req.(*PresignObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalStorageService_ReadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStorageServiceServer).ReadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalStorageService_ReadObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStorageServiceServer).ReadObject(ctx, req.(*ReadObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalStorageService_ServiceDesc is the grpc.ServiceDesc for InternalStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.InternalStorageService",
	HandlerType: (*InternalStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PresignObject",
			Handler:    _InternalStorageService_PresignObject_Handler,
		},
		{
			MethodName: "ReadObject",
			Handler:    _InternalStorageService_ReadObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}
