// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: data_gateway.proto

package cloudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataGatewayErrorCode int32

const (
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_UNSPECIFIED            DataGatewayErrorCode = 0
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_UNAUTHENTICATED        DataGatewayErrorCode = 1
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_FOUND       DataGatewayErrorCode = 2
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_OWNED       DataGatewayErrorCode = 3
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_REFRESHABLE DataGatewayErrorCode = 4
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_INVALID_ARGUMENT       DataGatewayErrorCode = 5
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_FAILED_PRECONDITION    DataGatewayErrorCode = 6
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_STS_UNAVAILABLE        DataGatewayErrorCode = 7
	DataGatewayErrorCode_DATA_GATEWAY_ERROR_CODE_INTERNAL_ERROR         DataGatewayErrorCode = 8
)

// Enum value maps for DataGatewayErrorCode.
var (
	DataGatewayErrorCode_name = map[int32]string{
		0: "DATA_GATEWAY_ERROR_CODE_UNSPECIFIED",
		1: "DATA_GATEWAY_ERROR_CODE_UNAUTHENTICATED",
		2: "DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_FOUND",
		3: "DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_OWNED",
		4: "DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_REFRESHABLE",
		5: "DATA_GATEWAY_ERROR_CODE_INVALID_ARGUMENT",
		6: "DATA_GATEWAY_ERROR_CODE_FAILED_PRECONDITION",
		7: "DATA_GATEWAY_ERROR_CODE_STS_UNAVAILABLE",
		8: "DATA_GATEWAY_ERROR_CODE_INTERNAL_ERROR",
	}
	DataGatewayErrorCode_value = map[string]int32{
		"DATA_GATEWAY_ERROR_CODE_UNSPECIFIED":            0,
		"DATA_GATEWAY_ERROR_CODE_UNAUTHENTICATED":        1,
		"DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_FOUND":       2,
		"DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_OWNED":       3,
		"DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_REFRESHABLE": 4,
		"DATA_GATEWAY_ERROR_CODE_INVALID_ARGUMENT":       5,
		"DATA_GATEWAY_ERROR_CODE_FAILED_PRECONDITION":    6,
		"DATA_GATEWAY_ERROR_CODE_STS_UNAVAILABLE":        7,
		"DATA_GATEWAY_ERROR_CODE_INTERNAL_ERROR":         8,
	}
)

func (x DataGatewayErrorCode) Enum() *DataGatewayErrorCode {
	p := new(DataGatewayErrorCode)
	*p = x
	return p
}

func (x DataGatewayErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataGatewayErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_data_gateway_proto_enumTypes[0].Descriptor()
}

func (DataGatewayErrorCode) Type() protoreflect.EnumType {
	return &file_data_gateway_proto_enumTypes[0]
}

func (x DataGatewayErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataGatewayErrorCode.Descriptor instead.
func (DataGatewayErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{0}
}

type UploadCredentials struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Bucket             string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Endpoint           string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ObjectKey          string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	StsAccessKeyId     string                 `protobuf:"bytes,4,opt,name=sts_access_key_id,json=stsAccessKeyId,proto3" json:"sts_access_key_id,omitempty"`
	StsAccessKeySecret string                 `protobuf:"bytes,5,opt,name=sts_access_key_secret,json=stsAccessKeySecret,proto3" json:"sts_access_key_secret,omitempty"`
	StsSecurityToken   string                 `protobuf:"bytes,6,opt,name=sts_security_token,json=stsSecurityToken,proto3" json:"sts_security_token,omitempty"`
	StsExpireAtUnix    int64                  `protobuf:"varint,7,opt,name=sts_expire_at_unix,json=stsExpireAtUnix,proto3" json:"sts_expire_at_unix,omitempty"`
	PartSizeBytes      int64                  `protobuf:"varint,8,opt,name=part_size_bytes,json=partSizeBytes,proto3" json:"part_size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadCredentials) Reset() {
	*x = UploadCredentials{}
	mi := &file_data_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCredentials) ProtoMessage() {}

func (x *UploadCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCredentials.ProtoReflect.Descriptor instead.
func (*UploadCredentials) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *UploadCredentials) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadCredentials) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UploadCredentials) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadCredentials) GetStsAccessKeyId() string {
	if x != nil {
		return x.StsAccessKeyId
	}
	return ""
}

func (x *UploadCredentials) GetStsAccessKeySecret() string {
	if x != nil {
		return x.StsAccessKeySecret
	}
	return ""
}

func (x *UploadCredentials) GetStsSecurityToken() string {
	if x != nil {
		return x.StsSecurityToken
	}
	return ""
}

func (x *UploadCredentials) GetStsExpireAtUnix() int64 {
	if x != nil {
		return x.StsExpireAtUnix
	}
	return 0
}

func (x *UploadCredentials) GetPartSizeBytes() int64 {
	if x != nil {
		return x.PartSizeBytes
	}
	return 0
}

type CreateFileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientHints   map[string]string      `protobuf:"bytes,1,rep,name=client_hints,json=clientHints,proto3" json:"client_hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileUploadRequest) Reset() {
	*x = CreateFileUploadRequest{}
	mi := &file_data_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileUploadRequest) ProtoMessage() {}

func (x *CreateFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileUploadRequest) GetClientHints() map[string]string {
	if x != nil {
		return x.ClientHints
	}
	return nil
}

type CreateFileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Credentials   *UploadCredentials     `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileUploadResponse) Reset() {
	*x = CreateFileUploadResponse{}
	mi := &file_data_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileUploadResponse) ProtoMessage() {}

func (x *CreateFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CreateFileUploadResponse) GetCredentials() *UploadCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RefreshUploadCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUploadCredentialsRequest) Reset() {
	*x = RefreshUploadCredentialsRequest{}
	mi := &file_data_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUploadCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUploadCredentialsRequest) ProtoMessage() {}

func (x *RefreshUploadCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUploadCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RefreshUploadCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshUploadCredentialsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type RefreshUploadCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Credentials   *UploadCredentials     `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUploadCredentialsResponse) Reset() {
	*x = RefreshUploadCredentialsResponse{}
	mi := &file_data_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUploadCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUploadCredentialsResponse) ProtoMessage() {}

func (x *RefreshUploadCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUploadCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RefreshUploadCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshUploadCredentialsResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *RefreshUploadCredentialsResponse) GetCredentials() *UploadCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type CompleteUploadRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UploadId           string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileSize           int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	RawTags            map[string]string      `protobuf:"bytes,5,rep,name=raw_tags,json=rawTags,proto3" json:"raw_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CompletedPartCount int32                  `protobuf:"varint,6,opt,name=completed_part_count,json=completedPartCount,proto3" json:"completed_part_count,omitempty"`
	OssObjectEtag      string                 `protobuf:"bytes,7,opt,name=oss_object_etag,json=ossObjectEtag,proto3" json:"oss_object_etag,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_data_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CompleteUploadRequest) GetRawTags() map[string]string {
	if x != nil {
		return x.RawTags
	}
	return nil
}

func (x *CompleteUploadRequest) GetCompletedPartCount() int32 {
	if x != nil {
		return x.CompletedPartCount
	}
	return 0
}

func (x *CompleteUploadRequest) GetOssObjectEtag() string {
	if x != nil {
		return x.OssObjectEtag
	}
	return ""
}

type CompleteUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResponse) Reset() {
	*x = CompleteUploadResponse{}
	mi := &file_data_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResponse) ProtoMessage() {}

func (x *CompleteUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadResponse) Descriptor() ([]byte, []int) {
	return file_data_gateway_proto_rawDescGZIP(), []int{6}
}

var File_data_gateway_proto protoreflect.FileDescriptor

const file_data_gateway_proto_rawDesc = "" +
	"\n" +
	"\x12data_gateway.proto\x12\x19archebase.data_gateway.v1\x1a\fcommon.proto\"\xc7\x02\n" +
	"\x11UploadCredentials\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12)\n" +
	"\x11sts_access_key_id\x18\x04 \x01(\tR\x0estsAccessKeyId\x121\n" +
	"\x15sts_access_key_secret\x18\x05 \x01(\tR\x12stsAccessKeySecret\x12,\n" +
	"\x12sts_security_token\x18\x06 \x01(\tR\x10stsSecurityToken\x12+\n" +
	"\x12sts_expire_at_unix\x18\a \x01(\x03R\x0fstsExpireAtUnix\x12&\n" +
	"\x0fpart_size_bytes\x18\b \x01(\x03R\rpartSizeBytes\"\xc1\x01\n" +
	"\x17CreateFileUploadRequest\x12f\n" +
	"\fclient_hints\x18\x01 \x03(\v2C.archebase.data_gateway.v1.CreateFileUploadRequest.ClientHintsEntryR\vclientHints\x1a>\n" +
	"\x10ClientHintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x18CreateFileUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12N\n" +
	"\vcredentials\x18\x02 \x01(\v2,.archebase.data_gateway.v1.UploadCredentialsR\vcredentialsJ\x04\b\x03\x10\x04\">\n" +
	"\x1fRefreshUploadCredentialsRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"\x95\x01\n" +
	" RefreshUploadCredentialsResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12N\n" +
	"\vcredentials\x18\x02 \x01(\v2,.archebase.data_gateway.v1.UploadCredentialsR\vcredentialsJ\x04\b\x03\x10\x04\"\xcd\x02\n" +
	"\x15CompleteUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12X\n" +
	"\braw_tags\x18\x05 \x03(\v2=.archebase.data_gateway.v1.CompleteUploadRequest.RawTagsEntryR\arawTags\x120\n" +
	"\x14completed_part_count\x18\x06 \x01(\x05R\x12completedPartCount\x12&\n" +
	"\x0foss_object_etag\x18\a \x01(\tR\rossObjectEtag\x1a:\n" +
	"\fRawTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\x04\x10\x05\"\x18\n" +
	"\x16CompleteUploadResponse*\xb4\x03\n" +
	"\x14DataGatewayErrorCode\x12'\n" +
	"#DATA_GATEWAY_ERROR_CODE_UNSPECIFIED\x10\x00\x12+\n" +
	"'DATA_GATEWAY_ERROR_CODE_UNAUTHENTICATED\x10\x01\x12,\n" +
	"(DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_FOUND\x10\x02\x12,\n" +
	"(DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_OWNED\x10\x03\x122\n" +
	".DATA_GATEWAY_ERROR_CODE_UPLOAD_NOT_REFRESHABLE\x10\x04\x12,\n" +
	"(DATA_GATEWAY_ERROR_CODE_INVALID_ARGUMENT\x10\x05\x12/\n" +
	"+DATA_GATEWAY_ERROR_CODE_FAILED_PRECONDITION\x10\x06\x12+\n" +
	"'DATA_GATEWAY_ERROR_CODE_STS_UNAVAILABLE\x10\a\x12*\n" +
	"&DATA_GATEWAY_ERROR_CODE_INTERNAL_ERROR\x10\b2\x9e\x03\n" +
	"\x12DataGatewayService\x12{\n" +
	"\x10CreateFileUpload\x122.archebase.data_gateway.v1.CreateFileUploadRequest\x1a3.archebase.data_gateway.v1.CreateFileUploadResponse\x12\x93\x01\n" +
	"\x18RefreshUploadCredentials\x12:.archebase.data_gateway.v1.RefreshUploadCredentialsRequest\x1a;.archebase.data_gateway.v1.RefreshUploadCredentialsResponse\x12u\n" +
	"\x0eCompleteUpload\x120.archebase.data_gateway.v1.CompleteUploadRequest\x1a1.archebase.data_gateway.v1.CompleteUploadResponseb\x06proto3"

var (
	file_data_gateway_proto_rawDescOnce sync.Once
	file_data_gateway_proto_rawDescData []byte
)

func file_data_gateway_proto_rawDescGZIP() []byte {
	file_data_gateway_proto_rawDescOnce.Do(func() {
		file_data_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_gateway_proto_rawDesc), len(file_data_gateway_proto_rawDesc)))
	})
	return file_data_gateway_proto_rawDescData
}

var file_data_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_gateway_proto_goTypes = []any{
	(DataGatewayErrorCode)(0),                // 0: archebase.data_gateway.v1.DataGatewayErrorCode
	(*UploadCredentials)(nil),                // 1: archebase.data_gateway.v1.UploadCredentials
	(*CreateFileUploadRequest)(nil),          // 2: archebase.data_gateway.v1.CreateFileUploadRequest
	(*CreateFileUploadResponse)(nil),         // 3: archebase.data_gateway.v1.CreateFileUploadResponse
	(*RefreshUploadCredentialsRequest)(nil),  // 4: archebase.data_gateway.v1.RefreshUploadCredentialsRequest
	(*RefreshUploadCredentialsResponse)(nil), // 5: archebase.data_gateway.v1.RefreshUploadCredentialsResponse
	(*CompleteUploadRequest)(nil),            // 6: archebase.data_gateway.v1.CompleteUploadRequest
	(*CompleteUploadResponse)(nil),           // 7: archebase.data_gateway.v1.CompleteUploadResponse
	nil,                                      // 8: archebase.data_gateway.v1.CreateFileUploadRequest.ClientHintsEntry
	nil,                                      // 9: archebase.data_gateway.v1.CompleteUploadRequest.RawTagsEntry
}
var file_data_gateway_proto_depIdxs = []int32{
	8, // 0: archebase.data_gateway.v1.CreateFileUploadRequest.client_hints:type_name -> archebase.data_gateway.v1.CreateFileUploadRequest.ClientHintsEntry
	1, // 1: archebase.data_gateway.v1.CreateFileUploadResponse.credentials:type_name -> archebase.data_gateway.v1.UploadCredentials
	1, // 2: archebase.data_gateway.v1.RefreshUploadCredentialsResponse.credentials:type_name -> archebase.data_gateway.v1.UploadCredentials
	9, // 3: archebase.data_gateway.v1.CompleteUploadRequest.raw_tags:type_name -> archebase.data_gateway.v1.CompleteUploadRequest.RawTagsEntry
	2, // 4: archebase.data_gateway.v1.DataGatewayService.CreateFileUpload:input_type -> archebase.data_gateway.v1.CreateFileUploadRequest
	4, // 5: archebase.data_gateway.v1.DataGatewayService.RefreshUploadCredentials:input_type -> archebase.data_gateway.v1.RefreshUploadCredentialsRequest
	6, // 6: archebase.data_gateway.v1.DataGatewayService.CompleteUpload:input_type -> archebase.data_gateway.v1.CompleteUploadRequest
	3, // 7: archebase.data_gateway.v1.DataGatewayService.CreateFileUpload:output_type -> archebase.data_gateway.v1.CreateFileUploadResponse
	5, // 8: archebase.data_gateway.v1.DataGatewayService.RefreshUploadCredentials:output_type -> archebase.data_gateway.v1.RefreshUploadCredentialsResponse
	7, // 9: archebase.data_gateway.v1.DataGatewayService.CompleteUpload:output_type -> archebase.data_gateway.v1.CompleteUploadResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_gateway_proto_init() }
func file_data_gateway_proto_init() {
	if File_data_gateway_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_gateway_proto_rawDesc), len(file_data_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_gateway_proto_goTypes,
		DependencyIndexes: file_data_gateway_proto_depIdxs,
		EnumInfos:         file_data_gateway_proto_enumTypes,
		MessageInfos:      file_data_gateway_proto_msgTypes,
	}.Build()
	File_data_gateway_proto = out.File
	file_data_gateway_proto_goTypes = nil
	file_data_gateway_proto_depIdxs = nil
}
