// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: data_gateway.proto

package cloudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataGatewayService_CreateFileUpload_FullMethodName         = "/archebase.data_gateway.v1.DataGatewayService/CreateFileUpload"
	DataGatewayService_RefreshUploadCredentials_FullMethodName = "/archebase.data_gateway.v1.DataGatewayService/RefreshUploadCredentials"
	DataGatewayService_CompleteUpload_FullMethodName           = "/archebase.data_gateway.v1.DataGatewayService/CompleteUpload"
)

// DataGatewayServiceClient is the client API for DataGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGatewayServiceClient interface {
	CreateFileUpload(ctx context.Context, in *CreateFileUploadRequest, opts ...grpc.CallOption) (*CreateFileUploadResponse, error)
	RefreshUploadCredentials(ctx context.Context, in *RefreshUploadCredentialsRequest, opts ...grpc.CallOption) (*RefreshUploadCredentialsResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
}

type dataGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayServiceClient(cc grpc.ClientConnInterface) DataGatewayServiceClient {
	return &dataGatewayServiceClient{cc}
}

func (c *dataGatewayServiceClient) CreateFileUpload(ctx context.Context, in *CreateFileUploadRequest, opts ...grpc.CallOption) (*CreateFileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CreateFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) RefreshUploadCredentials(ctx context.Context, in *RefreshUploadCredentialsRequest, opts ...grpc.CallOption) (*RefreshUploadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshUploadCredentialsResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_RefreshUploadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayServiceServer is the server API for DataGatewayService service.
// All implementations must embed UnimplementedDataGatewayServiceServer
// for forward compatibility.
type DataGatewayServiceServer interface {
	CreateFileUpload(context.Context, *CreateFileUploadRequest) (*CreateFileUploadResponse, error)
	RefreshUploadCredentials(context.Context, *RefreshUploadCredentialsRequest) (*RefreshUploadCredentialsResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	mustEmbedUnimplementedDataGatewayServiceServer()
}

// UnimplementedDataGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayServiceServer struct{}

func (UnimplementedDataGatewayServiceServer) CreateFileUpload(context.Context, *CreateFileUploadRequest) (*CreateFileUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFileUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) RefreshUploadCredentials(context.Context, *RefreshUploadCredentialsRequest) (*RefreshUploadCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshUploadCredentials not implemented")
}
func (UnimplementedDataGatewayServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) mustEmbedUnimplementedDataGatewayServiceServer() {}
func (UnimplementedDataGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeDataGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayServiceServer will
// result in compilation errors.
type UnsafeDataGatewayServiceServer interface {
	mustEmbedUnimplementedDataGatewayServiceServer()
}

func RegisterDataGatewayServiceServer(s grpc.ServiceRegistrar, srv DataGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedDataGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGatewayService_ServiceDesc, srv)
}

func _DataGatewayService_CreateFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CreateFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CreateFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CreateFileUpload(ctx, req.(*CreateFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_RefreshUploadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshUploadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).RefreshUploadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_RefreshUploadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).RefreshUploadCredentials(ctx, req.(*RefreshUploadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGatewayService_ServiceDesc is the grpc.ServiceDesc for DataGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DataGatewayService",
	HandlerType: (*DataGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileUpload",
			Handler:    _DataGatewayService_CreateFileUpload_Handler,
		},
		{
			MethodName: "RefreshUploadCredentials",
			Handler:    _DataGatewayService_RefreshUploadCredentials_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _DataGatewayService_CompleteUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}
