// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: data_gateway.proto

package cloudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataGatewayService_CreateLogicalUpload_FullMethodName      = "/archebase.data_gateway.v1.DataGatewayService/CreateLogicalUpload"
	DataGatewayService_GetUploadRecovery_FullMethodName        = "/archebase.data_gateway.v1.DataGatewayService/GetUploadRecovery"
	DataGatewayService_ReissueUploadCredentials_FullMethodName = "/archebase.data_gateway.v1.DataGatewayService/ReissueUploadCredentials"
	DataGatewayService_AbortUpload_FullMethodName              = "/archebase.data_gateway.v1.DataGatewayService/AbortUpload"
	DataGatewayService_CompleteUpload_FullMethodName           = "/archebase.data_gateway.v1.DataGatewayService/CompleteUpload"
)

// DataGatewayServiceClient is the client API for DataGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGatewayServiceClient interface {
	CreateLogicalUpload(ctx context.Context, in *CreateLogicalUploadRequest, opts ...grpc.CallOption) (*CreateLogicalUploadResponse, error)
	GetUploadRecovery(ctx context.Context, in *GetUploadRecoveryRequest, opts ...grpc.CallOption) (*GetUploadRecoveryResponse, error)
	ReissueUploadCredentials(ctx context.Context, in *ReissueUploadCredentialsRequest, opts ...grpc.CallOption) (*ReissueUploadCredentialsResponse, error)
	AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*AbortUploadResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
}

type dataGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayServiceClient(cc grpc.ClientConnInterface) DataGatewayServiceClient {
	return &dataGatewayServiceClient{cc}
}

func (c *dataGatewayServiceClient) CreateLogicalUpload(ctx context.Context, in *CreateLogicalUploadRequest, opts ...grpc.CallOption) (*CreateLogicalUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogicalUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CreateLogicalUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) GetUploadRecovery(ctx context.Context, in *GetUploadRecoveryRequest, opts ...grpc.CallOption) (*GetUploadRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadRecoveryResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_GetUploadRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) ReissueUploadCredentials(ctx context.Context, in *ReissueUploadCredentialsRequest, opts ...grpc.CallOption) (*ReissueUploadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReissueUploadCredentialsResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_ReissueUploadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*AbortUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_AbortUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, DataGatewayService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayServiceServer is the server API for DataGatewayService service.
// All implementations must embed UnimplementedDataGatewayServiceServer
// for forward compatibility.
type DataGatewayServiceServer interface {
	CreateLogicalUpload(context.Context, *CreateLogicalUploadRequest) (*CreateLogicalUploadResponse, error)
	GetUploadRecovery(context.Context, *GetUploadRecoveryRequest) (*GetUploadRecoveryResponse, error)
	ReissueUploadCredentials(context.Context, *ReissueUploadCredentialsRequest) (*ReissueUploadCredentialsResponse, error)
	AbortUpload(context.Context, *AbortUploadRequest) (*AbortUploadResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	mustEmbedUnimplementedDataGatewayServiceServer()
}

// UnimplementedDataGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayServiceServer struct{}

func (UnimplementedDataGatewayServiceServer) CreateLogicalUpload(context.Context, *CreateLogicalUploadRequest) (*CreateLogicalUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLogicalUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) GetUploadRecovery(context.Context, *GetUploadRecoveryRequest) (*GetUploadRecoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadRecovery not implemented")
}
func (UnimplementedDataGatewayServiceServer) ReissueUploadCredentials(context.Context, *ReissueUploadCredentialsRequest) (*ReissueUploadCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReissueUploadCredentials not implemented")
}
func (UnimplementedDataGatewayServiceServer) AbortUpload(context.Context, *AbortUploadRequest) (*AbortUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedDataGatewayServiceServer) mustEmbedUnimplementedDataGatewayServiceServer() {}
func (UnimplementedDataGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeDataGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayServiceServer will
// result in compilation errors.
type UnsafeDataGatewayServiceServer interface {
	mustEmbedUnimplementedDataGatewayServiceServer()
}

func RegisterDataGatewayServiceServer(s grpc.ServiceRegistrar, srv DataGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedDataGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGatewayService_ServiceDesc, srv)
}

func _DataGatewayService_CreateLogicalUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogicalUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CreateLogicalUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CreateLogicalUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CreateLogicalUpload(ctx, req.(*CreateLogicalUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_GetUploadRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).GetUploadRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_GetUploadRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).GetUploadRecovery(ctx, req.(*GetUploadRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_ReissueUploadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReissueUploadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).ReissueUploadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_ReissueUploadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).ReissueUploadCredentials(ctx, req.(*ReissueUploadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_AbortUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).AbortUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_AbortUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).AbortUpload(ctx, req.(*AbortUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGatewayService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGatewayService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGatewayService_ServiceDesc is the grpc.ServiceDesc for DataGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archebase.data_gateway.v1.DataGatewayService",
	HandlerType: (*DataGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLogicalUpload",
			Handler:    _DataGatewayService_CreateLogicalUpload_Handler,
		},
		{
			MethodName: "GetUploadRecovery",
			Handler:    _DataGatewayService_GetUploadRecovery_Handler,
		},
		{
			MethodName: "ReissueUploadCredentials",
			Handler:    _DataGatewayService_ReissueUploadCredentials_Handler,
		},
		{
			MethodName: "AbortUpload",
			Handler:    _DataGatewayService_AbortUpload_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _DataGatewayService_CompleteUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_gateway.proto",
}
