name: Documentation Request
description: Request improvements or additions to Keystone documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Keystone's documentation! Clear documentation is essential for a great user experience.

  - type: textarea
    id: what-needs-documenting
    attributes:
      label: What Needs Documentation?
      description: What aspect of Keystone needs better documentation?
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation improvement is needed?
      options:
        - New documentation page
        - Improve existing documentation
        - Add code examples
        - Add diagrams/visualizations
        - Fix errors or inaccuracies
        - Add translation
        - API reference
        - Tutorial/Guide
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who is this documentation for?
      options:
        - New users (getting started)
        - System integrators
        - Contributors
        - Advanced users
        - All users
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What is the current state of the documentation for this topic?
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: What specific improvements would you like to see?
    validations:
      required: true

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content (Optional)
      description: If you have specific content or examples in mind, please share
    validations:
      required: false

  - type: textarea
    id: location
    attributes:
      label: Suggested Location
      description: Where should this documentation be added?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to write this documentation
          required: false
        - label: I am willing to review documentation drafts
          required: false
        - label: I have experience with technical writing
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing documentation for similar content
          required: true
        - label: This documentation request aligns with the project scope
          required: false
