apiVersion: v1
kind: Service
metadata:
  name: {{ include "keystone-stack.componentName" (list . "mysql") }}
  labels:
    {{- include "keystone-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  {{- with .Values.mysql.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "keystone-stack.selectorLabels" (list . "mysql") | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
