{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keystone-stack.serviceAccountName" . }}
  labels:
    {{- include "keystone-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: keystone
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
